[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[shell]
program = "ubuntu"
